name: 'grizlyyyraa_dart'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/grizlyyyraa'
repository: 'https://github.com/{main_username_owner}/grizlyyyraa'
issue_tracker: 'https://github.com/{main_username_owner}/grizlyyyraa/issues'
documentation: 'https://github.com/{main_username_owner}/grizlyyyraa/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/{main_username_owner}'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
dependencies: 
  path: '^1.9.0'
  universal_io: '^2.2.2'
  grizlyyyraa: '^0.0.0'
  grizlyyyraa_scheme: '^0.0.0'
  mason_logger: '^0.2.5'
  collection: '^1.18.0'
  yaml: '^3.1.2'
  yaml_writer: '^2.0.0'
  general_lib: '^0.0.42'
dev_dependencies: 
  lints: '^2.1.0'
  test: '^1.24.0'
executables: 
  grizlyyyraa_dart: 'grizlyyyraa_dart'
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
