name: 'grizlyyyraa_android'
description: 'A sample command-line application.'
version: '0.0.0'
homepage: 'https://github.com/{main_username_owner}/grizlyyyraa'
repository: 'https://github.com/{main_username_owner}/grizlyyyraa'
issue_tracker: 'https://github.com/{main_username_owner}/grizlyyyraa/issues'
documentation: 'https://github.com/{main_username_owner}/grizlyyyraa/tree/main/docs'
funding: 
  - 'https://github.com/sponsors/{main_username_owner}'
  - 'https://github.com/sponsors/{main_username_owner}'
platforms: 
  android: null
  ios: null
  linux: null
  macos: null
  web: null
  windows: null
environment: 
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=1.17.0'
dependencies: 
  flutter: 
    sdk: 'flutter'
dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'
  flutter_lints: '^2.0.0'
flutter: null
publish_to: 'none'
dependency_overrides: 
  pointycastle: '3.8.0'
